openapi: 3.0.3
info:
  title: TODO API overview
  description: TODOリストを管理するAPI
  version: 1.0.0
servers:
  - url: "https://uftqq91sl9.execute-api.ap-northeast-1.amazonaws.com/"
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "For more information, see https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-userpools-server-contract-reference.html"
      flows:
        authorizationCode:
          authorizationUrl: "https://my-todo-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/authorize"
          tokenUrl: "https://my-todo-dev.auth.ap-northeast-1.amazoncognito.com/oauth2/token"
          scopes:
            openid: openid token
  schemas:
    TaskInfoResponse:
      description: ""
      type: object
      x-examples:
        example:
          id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
          completed: true
          tittle: string
          body: string
          priority: 1
      properties:
        id:
          type: string
          minLength: 1
          format: uuid
        completed:
          type: boolean
        tittle:
          type: string
          minLength: 1
        body:
          type: string
        priority:
          type: number
      required:
        - id
        - completed
        - tittle
        - priority
security:
  - OAuth2:
      - openid
      - token
paths:
  /tasks:
    get:
      summary: タスクの一覧を取得
      operationId: getTasks
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ""
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - id
                    - completed
                    - tittle
                    - priority
                  properties:
                    id:
                      type: string
                      minLength: 1
                    completed:
                      type: boolean
                    tittle:
                      type: string
                      minLength: 1
                    priority:
                      type: number
                x-examples:
                  example-1:
                    - id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                      completed: false
                      tittle: コーヒー豆を買う
                      priority: 1
                    - id: 81bcf5bc-7afc-aa06-a860-622222df84f3
                      completed: true
                      tittle: ドーナッツを買う
                      priority: 2
              examples:
                example:
                  value:
                    - id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                      completed: false
                      tittle: コーヒー豆を買う
                      priority: 1
                    - id: 81bcf5bc-7afc-aa06-a860-622222df84f3
                      completed: true
                      tittle: ドーナッツを買う
                      priority: 2
        "401":
          description: Unauthorized
      description: ユーザーに紐づくタスクの一覧を返します。このレスポンスはタスクのタイトルを含みますが、タスクの内容を含みません。
    post:
      summary: タスクを登録
      operationId: postTasks
      requestBody:
        content:
          application/json:
            schema:
              description: ""
              type: object
              x-examples:
                example-1:
                  tittle: string
                  body: string
              properties:
                tittle:
                  type: string
                  minLength: 1
                body:
                  type: string
                priority:
                  type: integer
              required:
                - tittle
                - priority
            examples:
              example:
                value:
                  tittle: コーヒー豆を買う
                  body: いつものコーヒーショップでブレンドを100g
                  priority: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskInfoResponse"
              examples:
                example:
                  value:
                    id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                    completed: false
                    tittle: コーヒー豆を買う
                    body: いつものコーヒーショップでブレンドを100g
                    priority: 1
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      description: 新規タスクを登録します。レスポンスとして、登録されたタスクの詳細情報を返します。
  "/tasks/{id}":
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: タスクを指定して取得
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskInfoResponse"
              examples:
                example:
                  value:
                    id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                    completed: false
                    tittle: コーヒー豆を買う
                    body: いつものコーヒーショップでブレンドを100g
                    priority: 1
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      operationId: getTaskByid
      description: IDで指定されたタスクの詳細を返します。詳細にはタスクのタイトル、内容がともに含まれます （内容は存在する場合のみ）。他のユーザーのタスクは指定できません。
    put:
      summary: タスクを指定して更新
      operationId: putTask
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskInfoResponse"
              examples:
                example:
                  value:
                    id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                    completed: true
                    tittle: コーヒー豆を買う
                    body: いつものコーヒーショップでブレンドを100g
                    priority: 1
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              description: ""
              type: object
              x-examples:
                example-1:
                  id: e6e9d88a-9b63-468a-aec3-b7a11de27af8
                  completed: true
                  tittle: string
                  body: string
              properties:
                completed:
                  type: boolean
                tittle:
                  type: string
                  minLength: 1
                body:
                  type: string
                priority:
                  type: integer
              required:
                - completed
                - tittle
                - priority
            examples:
              example:
                value:
                  completed: true
                  tittle: コーヒー豆を買う
                  body: いつものコーヒーショップでブレンドを100g
                  priority: 1
        description: ""
      description: IDで指定されたタスクを更新します。レスポンスとして、更新されたタスクの詳細情報を返します。他のユーザーのタスクは指定できません。
    delete:
      summary: タスクを指定して削除
      operationId: deleteTask
      responses:
        "204":
          description: No Content
          content:
            application/json:
              schema:
                type: object
                properties: {}
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      description: "IDで指定されたタスクを削除します。レスポンスとして空のオブジェクト`{}`を受け取ります。他のユーザーのタスクは指定できません。"
