name: cdk

on:
  push:
    branches:
      - main
      - release
  pull_request:
env:
  AWS_REGION: ${{secrets.AWS_REGION}}
permissions:
  id-token: write
  contents: write
jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check release branch
        if: ${{ github.base_ref == 'release' || github.ref == 'refs/heads/release' }}
        run: echo "SYSTEM_ENV=prd" >> $GITHUB_ENV

      - name: Check main branch
        if: ${{ github.base_ref == 'main' || github.ref == 'refs/heads/main' }}
        run: echo "SYSTEM_ENV=stg" >> $GITHUB_ENV

      - name: Setup environment variables
        run: |
          echo ${{github.base_ref}}
          echo AMPLIFY_URL=${{secrets.AMPLIFY_URL}} >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: ${{env.AWS_REGION}}

      - name: Unit tests
        if: contains(github.event_name, 'pull_request')
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          npm run test

      - name: CDK Diff Check
        if: contains(github.event_name, 'pull_request')
        run: npm run cdk diff

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run deploy
